# 应用名称
spring:
  application:
    name: Online_Judge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://121.37.137.154:26000/online_judge?useUnicode=true&characterEncoding=UTF-8&currentSchema=formal_db
#    url: jdbc:postgresql://192.168.0.112:26000/online_judge?useUnicode=true&characterEncoding=UTF-8&currentSchema=formal_db
    username: team
    password: 4C7A63abcd!
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package:
    com.test.mybatisplus.enums
# 应用服务 WEB 访问端口
server:
  port: 8181

